static const char* g_2DShape_vertexshader = 
	"#version 140\n"
	"\n"
	"in vec4 position;\n"
	"in uint inColor;\n"
	"in uint Flags;\n"
	"in vec3 location3; // cneter of the cercul / texture \n"
	"// so , what ever tringel it passed; all what we will do is rotate it, whet ever position, to save the poor cpu frome some procesing cyculs\n"
	"\n"
	"//out pos;\n"
	"flat out uint color;\n"
	"flat out uint flags;\n"
	"out vec4 pos;\n"
	"out vec2 texCoord;\n"
	"\n"
	"uniform mat4 u_MVP;\n"
	"\n"
	"\n"
	"vec2 Rotate(vec2 pos_,vec2 center,float theta){\n"
	"	float raduian=(theta*3.14159)/(180.0);\n"
	"	float X = pos_.x-center.x;\n"
	"	float Y = pos_.y-center.y;\n"
	"	float posx=center.x+X*cos(raduian)-Y*sin(raduian);\n"
	"	float posy=center.y+X*sin(raduian)+Y*cos(raduian);\n"
	"	return vec2(posx,posy);\n"
	"}\n"
	"\n"
	"\n"
	"void main(){\n"
	"	vec4 posi=position;\n"
	"	if( (Flags & 0xfu) == uint(1)){\n"
	"		posi.xy= Rotate(position.xy,location3.xy,location3.z); // the thread float of 'location3' will hold the theta\n"
	"	}else if( (Flags & 0x10u) > uint(0)){\n"
	"		texCoord = location3.xy;\n"
	"	}\n"
	"	gl_Position= u_MVP*posi;//vec4(posi.x/800.0,posi.y/600.0,posi.zw);\n"
	"	pos=posi;\n"
	"	flags=Flags;\n"
	"	color=inColor;\n"
	"}\n"
	;


/********************************************g_2DShape_fragmentshader***********************************************/
static const char* g_2DShape_fragmentshader = 
	"#version 140\n"
	"out vec4 outcl;\n"
	"\n"
	"\n"
	"flat in uint color;\n"
	"\n"
	"flat in uint flags;\n"
	"in vec4 pos;\n"
	"in vec2 texCoord;\n"
	"/*flags bit structure\n"
	"	|0123|  -> Praticul\n"
	"	|4|     -> texture Enbled\n"
	"	|56789| -> texture slot\n"
	"	|10->31| ->reseved\n"
	"*/\n"
	"\n"
	"uniform sampler2D texture0;\n"
	"uniform sampler2D texture1;\n"
	"uniform sampler2D texture2;\n"
	"uniform sampler2D texture3;\n"
	"uniform sampler2D texture4;\n"
	"uniform sampler2D texture5;\n"
	"uniform sampler2D texture6;\n"
	"uniform sampler2D texture7;\n"
	"uniform sampler2D texture8;\n"
	"uniform sampler2D texture9;\n"
	"uniform sampler2D texture10;\n"
	"uniform sampler2D texture11;\n"
	"uniform sampler2D texture12;\n"
	"uniform sampler2D texture13;\n"
	"uniform sampler2D texture14;\n"
	"uniform sampler2D texture15;\n"
	"uniform sampler2D texture16;\n"
	"uniform sampler2D texture17;\n"
	"uniform sampler2D texture18;\n"
	"uniform sampler2D texture19;\n"
	"uniform sampler2D texture20;\n"
	"uniform sampler2D texture21;\n"
	"uniform sampler2D texture22;\n"
	"uniform sampler2D texture23;\n"
	"uniform sampler2D texture24;\n"
	"uniform sampler2D texture25;\n"
	"uniform sampler2D texture26;\n"
	"uniform sampler2D texture27;\n"
	"uniform sampler2D texture28;\n"
	"uniform sampler2D texture29;\n"
	"uniform sampler2D texture30;\n"
	"uniform sampler2D texture31;\n"
	"void main(){\n"
	"	float r = float((color>>24)&0xffu)/255.0;\n"
	"	float g = float((color>>16)&0xffu)/255.0;\n"
	"	float b = float((color>>8)&0xffu)/255.0;\n"
	"	float a = float(color&0xffu)/255.0;\n"
	"	\n"
	"	if( (flags & 0x10u) > uint(0)){// it is a texture\n"
	"		int tex = int((flags>>5)&0x1fu);\n"
	"		if      (tex==0)  {outcl=texture(texture0  ,texCoord);}\n"
	"		else if (tex==1)  {outcl=texture(texture1  ,texCoord);}\n"
	"		else if (tex==2)  {outcl=texture(texture2  ,texCoord);}\n"
	"		else if (tex==3)  {outcl=texture(texture3  ,texCoord);}\n"
	"		else if (tex==4)  {outcl=texture(texture4  ,texCoord);}\n"
	"		else if (tex==5)  {outcl=texture(texture5  ,texCoord);}\n"
	"		else if (tex==6)  {outcl=texture(texture6  ,texCoord);}\n"
	"		else if (tex==7)  {outcl=texture(texture7  ,texCoord);}\n"
	"		else if (tex==8)  {outcl=texture(texture8  ,texCoord);}\n"
	"		else if (tex==9)  {outcl=texture(texture9  ,texCoord);}\n"
	"		else if (tex==10) {outcl=texture(texture10 ,texCoord);}\n"
	"		else if (tex==11) {outcl=texture(texture11 ,texCoord);}\n"
	"		else if (tex==12) {outcl=texture(texture12 ,texCoord);}\n"
	"		else if (tex==13) {outcl=texture(texture13 ,texCoord);}\n"
	"		else if (tex==14) {outcl=texture(texture14 ,texCoord);}\n"
	"		else if (tex==15) {outcl=texture(texture15 ,texCoord);}\n"
	"		else if (tex==16) {outcl=texture(texture16 ,texCoord);}\n"
	"		else if (tex==17) {outcl=texture(texture17 ,texCoord);}\n"
	"		else if (tex==18) {outcl=texture(texture18 ,texCoord);}\n"
	"		else if (tex==19) {outcl=texture(texture19 ,texCoord);}\n"
	"		else if (tex==20) {outcl=texture(texture20 ,texCoord);}\n"
	"		else if (tex==21) {outcl=texture(texture21 ,texCoord);}\n"
	"		else if (tex==22) {outcl=texture(texture22 ,texCoord);}\n"
	"		else if (tex==23) {outcl=texture(texture23 ,texCoord);}\n"
	"		else if (tex==24) {outcl=texture(texture24 ,texCoord);}\n"
	"		else if (tex==25) {outcl=texture(texture25 ,texCoord);}\n"
	"		else if (tex==26) {outcl=texture(texture26 ,texCoord);}\n"
	"		else if (tex==27) {outcl=texture(texture27 ,texCoord);}\n"
	"		else if (tex==28) {outcl=texture(texture28 ,texCoord);}\n"
	"		else if (tex==29) {outcl=texture(texture29 ,texCoord);}\n"
	"		else if (tex==30) {outcl=texture(texture30 ,texCoord);}\n"
	"		else if (tex==31) {outcl=texture(texture31 ,texCoord);}\n"
	"		else {return;}	\n"
	"		outcl.r*=r;\n"
	"		outcl.g*=g;\n"
	"		outcl.b*=b;\n"
	"		outcl.a*=a;\n"
	"		\n"
	"		//outcl.a=outcl.a*a+a*(1.0-a);\n"
	"		//yeah that is auto generated, i know that this is not the best way to make it, opengl is aginst me rigth know\n"
	"		//TODO: i dont even have to tell you what to do, bruh\n"
	"		return;	\n"
	"	}\n"
	"	\n"
	"	outcl =vec4(r,g,b,a);\n"
	"	\n"
	"}\n"
	;//Converted by File2.H!
